<#
.SYNOPSIS
  Build a UEFI ESP that boots KazuOS through the Limine bootloader (chain-load).

.DESCRIPTION
  Layout produced under -EspDir:

    EFI/BOOT/BOOTX64.EFI               Limine (firmware boot entry)
    EFI/BOOT/limine.conf               efi_chainload entry -> KazuOS bootloader
    EFI/KazuOS/kazuos-bootloader.efi   the KazuOS UEFI bootloader (chain-loaded)
    KazuOS/kernel.elf, initrd.kfs, font.ttf   loaded by the KazuOS bootloader

  The KazuOS bootloader reads \KazuOS\* via the volume it was loaded from, so it
  still finds the kernel/initrd at the ESP root after being moved into EFI/KazuOS.

  The Limine EFI binary is a third-party prebuilt; it is cached (untracked) under
  tools/limine and auto-downloaded from the pinned release if missing. The
  limine.conf is generated here so the boot config stays in version control.
#>
param(
    [Parameter(Mandatory = $true)][string]$EspDir,
    [Parameter(Mandatory = $true)][string]$BootloaderEfi,
    [Parameter(Mandatory = $true)][string]$KernelElf,
    [Parameter(Mandatory = $true)][string]$InitrdKfs,
    [string]$FontTtf
)

$ErrorActionPreference = "Stop"

$LimineVersion = "v12.3.3"
$CacheDir  = Join-Path $PSScriptRoot "tools\limine"
$LimineEfi = Join-Path $CacheDir "BOOTX64.EFI"

# Fetch + cache the Limine EFI binary if not already present.
if (-not (Test-Path $LimineEfi)) {
    Write-Host "  Downloading Limine $LimineVersion (one-time)..."
    New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
    $zipUrl = "https://github.com/limine-bootloader/limine/releases/download/$LimineVersion/limine-binary.zip"
    $zipPath = Join-Path $CacheDir "limine-binary.zip"
    $extract = Join-Path $CacheDir "extract"
    Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
    if (Test-Path $extract) { Remove-Item $extract -Recurse -Force }
    Expand-Archive -Path $zipPath -DestinationPath $extract -Force
    $found = Get-ChildItem $extract -Recurse -Filter "BOOTX64.EFI" | Select-Object -First 1
    if (-not $found) { throw "BOOTX64.EFI not found in Limine package." }
    Copy-Item $found.FullName $LimineEfi -Force
    Remove-Item $zipPath -Force
    Remove-Item $extract -Recurse -Force
}

if (-not (Test-Path $BootloaderEfi)) { throw "Bootloader not found: $BootloaderEfi" }
if (-not (Test-Path $KernelElf))     { throw "Kernel not found: $KernelElf" }
if (-not (Test-Path $InitrdKfs))     { throw "initrd.kfs not found: $InitrdKfs" }

if (Test-Path $EspDir) { Remove-Item $EspDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path `
    (Join-Path $EspDir "EFI\BOOT"), (Join-Path $EspDir "EFI\KazuOS"), (Join-Path $EspDir "KazuOS") | Out-Null

# Limine = firmware boot entry.
Copy-Item $LimineEfi (Join-Path $EspDir "EFI\BOOT\BOOTX64.EFI") -Force

# limine.conf: after the timeout, chainload the KazuOS bootloader. boot():/ is the
# volume Limine was loaded from (the ESP), where \KazuOS\kernel.elf also lives.
@"
# Limine -> KazuOS chainload (generated by setup_limine_esp.ps1).
timeout: 1

/KazuOS
    protocol: efi_chainload
    path: boot():/EFI/KazuOS/kazuos-bootloader.efi
"@ | Set-Content -Path (Join-Path $EspDir "EFI\BOOT\limine.conf") -Encoding ASCII

# KazuOS bootloader, moved out of EFI/BOOT (Limine owns that slot now).
Copy-Item $BootloaderEfi (Join-Path $EspDir "EFI\KazuOS\kazuos-bootloader.efi") -Force

# Payload the KazuOS bootloader loads from the ESP root.
Copy-Item $KernelElf (Join-Path $EspDir "KazuOS\kernel.elf") -Force
Copy-Item $InitrdKfs (Join-Path $EspDir "KazuOS\initrd.kfs") -Force
if ($FontTtf -and (Test-Path $FontTtf)) {
    Copy-Item $FontTtf (Join-Path $EspDir "KazuOS\font.ttf") -Force
}

Write-Host "  Limine ESP ready at $EspDir (boot: Limine -> EFI/KazuOS/kazuos-bootloader.efi)"
