extern crate alloc;

use alloc::vec;
use alloc::string;
use alloc::boxed;
use alloc::borrow::ToOwned;
use alloc::format;
use core::fmt::Write;

include!("../kernel/src/syscall_numbers.rs");

pub struct KazuWriter;

impl Write for KazuWriter {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        sys_write_raw(s.as_bytes());
        Ok(())
    }
}

#[macro_export]
macro_rules! print {
    ($($arg:tt)*) => {{
        use core::fmt::Write;
        let _ = write!(KazuWriter, $($arg)*);
    }};
}

#[macro_export]
macro_rules! println {
    () => { sys_write_raw(b"\r\n") };
    ($($arg:tt)*) => {{
        use core::fmt::Write;
        let _ = write!(KazuWriter, $($arg)*);
        sys_write_raw(b"\r\n");
    }};
}

/// Metadata returned by kkm_info().
#[repr(C)]
pub struct KkmInfo {
    pub name:    &'static str,
    /// Null-terminated list of module names this module depends on.
    pub depends: &'static [&'static str],
}

/// Module entry point generated by module_runtime. Calls the module's four
/// lifecycle functions in order:
///   kkm_info()  — metadata query (not called here, used by build tooling)
///   kkm_init()  — hardware initialisation, returns false on failure
///   kkm_run()   — main event loop, returns when a stop signal is received
///   kkm_exit()  — cleanup
#[no_mangle]
pub extern "C" fn _start(_argc: u64, _argv: u64) -> ! {
    // Enable signal catching so kmod::unload() can reach us.
    sys_signal_catch(true);

    if !kkm_init() {
        sys_exit(1);
    }

    kkm_run();
    kkm_exit();
    sys_exit(0);
}

#[panic_handler]
fn panic_handler(info: &core::panic::PanicInfo) -> ! {
    print!("[KKM PANIC] ");
    let _ = write!(KazuWriter, "{}", info.message());
    print!("\r\n");
    sys_exit(1)
}

#[global_allocator]
static ALLOC: KazuAlloc = KazuAlloc;

struct KazuAlloc;

unsafe impl core::alloc::GlobalAlloc for KazuAlloc {
    unsafe fn alloc(&self, layout: core::alloc::Layout) -> *mut u8 {
        let ptr = sys_heap_alloc(layout.size() as u64);
        if ptr == 0 { return core::ptr::null_mut(); }
        ptr as *mut u8
    }

    unsafe fn dealloc(&self, ptr: *mut u8, _layout: core::alloc::Layout) {
        sys_heap_free(ptr as u64);
    }
}

// ── syscall helpers ──────────────────────────────────────────────────────────

fn sys_write_raw(buf: &[u8]) {
    unsafe {
        core::arch::asm!(
            "int 0x80",
            in("rax") SYS_CONSOLE_WRITE,
            in("rdi") buf.as_ptr(),
            in("rsi") buf.len(),
            in("rdx") 0u64,
            lateout("rax") _,
        );
    }
}

pub fn sys_exit(code: u64) -> ! {
    unsafe {
        core::arch::asm!(
            "int 0x80",
            in("rax") SYS_EXIT,
            in("rdi") code,
            in("rsi") 0u64,
            in("rdx") 0u64,
            lateout("rax") _,
        );
    }
    loop {}
}

/// Block until the next timer tick fires. Use for polling drivers in non-IOAPIC mode.
pub fn sys_sleep_tick() {
    unsafe {
        core::arch::asm!(
            "int 0x80",
            in("rax") SYS_SLEEP,
            in("rdi") 1u64,
            in("rsi") SLEEP_UNIT_TICK,
            in("rdx") 0u64,
            lateout("rax") _,
        );
    }
}

pub fn sys_sleep(ms: u64) {
    unsafe {
        core::arch::asm!(
            "int 0x80",
            in("rax") SYS_SLEEP,
            in("rdi") ms,
            in("rsi") SLEEP_UNIT_MS,
            in("rdx") 0u64,
            lateout("rax") _,
        );
    }
}

pub fn sys_signal_catch(enable: bool) {
    unsafe {
        core::arch::asm!(
            "int 0x80",
            in("rax") SYS_SIGNAL_CATCH,
            in("rdi") enable as u64,
            in("rsi") 0u64,
            in("rdx") 0u64,
            lateout("rax") _,
        );
    }
}

/// Returns true if a stop signal is pending (clears the flag).
pub fn sys_signal_check() -> bool {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_SIGNAL_CHECK => r,
            in("rdi") 0u64,
            in("rsi") 0u64,
            in("rdx") 0u64,
        );
    }
    r != 0
}

/// Block until the given IRQ fires (or a stop signal wakes us).
/// Returns true on IRQ, false if interrupted by signal.
pub fn sys_irq_wait(irq: u8) -> bool {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_IRQ_WAIT => r,
            in("rdi") irq as u64,
            in("rsi") 0u64,
            in("rdx") 0u64,
        );
    }
    r != u64::MAX
}

/// Request access to `count` consecutive I/O ports starting at `port`.
pub fn sys_ioport_request(port: u16, count: u16) -> bool {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_IOPORT_REQUEST => r,
            in("rdi") port as u64,
            in("rsi") count as u64,
            in("rdx") 0u64,
        );
    }
    r != u64::MAX
}

pub fn sys_heap_alloc(size: u64) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_HEAP_ALLOC => r,
            in("rdi") size,
            in("rsi") 0u64,
            in("rdx") 0u64,
        );
    }
    r
}

pub fn sys_heap_free(ptr: u64) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_HEAP_FREE => r,
            in("rdi") ptr,
            in("rsi") 0u64,
            in("rdx") 0u64,
        );
    }
    r
}

/// Load a kernel module by path. Returns module_id on success, u64::MAX on failure.
pub fn sys_module_load(path: &[u8]) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_MODULE_LOAD => r,
            in("rdi") path.as_ptr(),
            in("rsi") path.len(),
            in("rdx") 0u64,
        );
    }
    r
}

/// Unload a kernel module by id. Returns true on success.
pub fn sys_module_unload(id: u64) -> bool {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_MODULE_UNLOAD => r,
            in("rdi") id,
            in("rsi") 0u64,
            in("rdx") 0u64,
        );
    }
    r != u64::MAX
}

/// Fill `buf` with module list entries (48 bytes each). Returns entry count.
pub fn sys_module_list(buf: &mut [u8]) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_MODULE_LIST => r,
            in("rdi") buf.as_mut_ptr(),
            in("rsi") buf.len(),
            in("rdx") 0u64,
        );
    }
    r
}

/// Fill `buf` (48 bytes) with info for module `id`. Returns true on success.
pub fn sys_module_info(id: u64, buf: &mut [u8]) -> bool {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_MODULE_INFO => r,
            in("rdi") id,
            in("rsi") buf.as_mut_ptr(),
            in("rdx") 0u64,
        );
    }
    r != u64::MAX
}

/// Open (or create) a named IPC channel. Returns channel id, or u64::MAX on error.
pub fn sys_ipc_open(name: &[u8]) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_IPC_OPEN => r,
            in("rdi") name.as_ptr(),
            in("rsi") name.len(),
            in("rdx") 0u64,
        );
    }
    r
}

/// Send data to an IPC channel. Blocks if queue is full.
pub fn sys_ipc_send(channel: u64, data: &[u8]) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_IPC_SEND => r,
            in("rdi") channel,
            in("rsi") data.as_ptr(),
            in("rdx") data.len(),
        );
    }
    r
}

/// Receive data from an IPC channel. Blocks until a message arrives.
pub fn sys_ipc_recv(channel: u64, buf: &mut [u8]) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") SYS_IPC_RECV => r,
            in("rdi") channel,
            in("rsi") buf.as_mut_ptr(),
            in("rdx") buf.len(),
        );
    }
    r
}

pub fn syscall(n: u64, a0: u64, a1: u64, a2: u64) -> u64 {
    let r: u64;
    unsafe {
        core::arch::asm!(
            "int 0x80",
            inlateout("rax") n => r,
            in("rdi") a0,
            in("rsi") a1,
            in("rdx") a2,
        );
    }
    r
}
